version: '3.8'

services:
  app:
    build:
      context: .
      args:
        ENV: "dev"
        DEBUG: true
    image: 4erk/swoole-app:dev
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_SESSION: "PHPSTORM"
    volumes:
      - ./:/var/www
    ports:
      - "80:9501"