services:
  app:
    build:
      context: .
      args:
        ENV: "DEVELOP"
        DEBUG: true
    image: 4erk/swoole-app:dev
    environment:
      ENV: "DEVELOP"
      BOOT: "SERVICE"
      SWOOLE_TIMEZONE: "UTC"
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_SESSION: "PHPSTORM"
    volumes:
      - ./:/var/www
    ports:
      - "80:9501"