version: '3.8'

services:
  app:
    build:
      context: .
      args:
        ENV: "prod"
        DEBUG: false
    image: 4erk/swoole-app:latest
    volumes:
      - ./:/var/www
    ports:
      - "80:9501"